apiVersion: v1
kind: Service
metadata:
  name: openlab-website
  namespace: openlab
  labels:
    app.kubernetes.io/name: openlab-website
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openlab-website
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
