apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openlab-website.fullname" . }}-config
  labels:
    {{- include "openlab-website.labels" . | nindent 4 }}
data:
  NODE_ENV: 'production'
  REDIS_URL: 'redis://redis-master.{{ .Release.Namespace }}.svc.cluster.local:6379'
  MINIO_ENDPOINT: 'minio.{{ .Release.Namespace }}.svc.cluster.local:9000'
  MINIO_BUCKET: 'openlab-media'
  MINIO_USE_SSL: 'false'
  MEILISEARCH_URL: 'http://{{ include "openlab-website.fullname" . }}-meilisearch.{{ .Release.Namespace }}.svc.cluster.local:7700'
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
