apiVersion: v1
kind: ServiceAccount
metadata:
  name: { { include "openlab-website.serviceAccountName" . } }
  labels: { { - include "openlab-website.labels" . | nindent 4 } }
automountServiceAccountToken: false
