apiVersion: v1
kind: Service
metadata:
  name: { { include "openlab-website.fullname" . } }
  labels: { { - include "openlab-website.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  selector: { { - include "openlab-website.selectorLabels" . | nindent 4 } }
  ports:
    - name: http
      port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
